version: '3.9'
services:
  edcb-wine:
    image: edcb-wine
    container_name: EDCB-Wine
    build:
      context: ./EDCB-Wine
    # OS 起動時にコンテナを自動起動する
    restart: always
    # ネットワークをホスト側と共有する
    # 標準の bridge モード (仮想ネットワーク) だと localhost との通信が面倒
    network_mode: host
    # Xfce のデスクトップ環境はなぜか特権モードでないと正常に動作しない
    privileged: true
    # ボリュームのマウント設定
    # /mnt/ はコンテナ内の EDCB からホストマシンに接続されている HDD にアクセスするために必要
    # 別途 HDD を /mnt/ 以下に適切な権限でマウントしておく必要がある (トラブル回避のため 777 (drwxrwxrwx) に設定することを推奨)
    volumes:
      - type: bind
        source: './EDCB-Wine/EDCB/'
        target: '/EDCB/'
      - type: bind
        source: '/mnt/'
        target: '/mnt/'
      - type: bind
        source: './Amatsukaze/cron/queue/'
        target: '/Amatsukaze/cron/queue/'
  
  amatsukaze:
    image: amatsukaze
    container_name: Amatsukaze
    build:
      context: ./Amatsukaze
    restart: always
    volumes:
      - type: bind
        source: './Amatsukaze/'
        target: '/Amatsukaze/'
    # 複数コマンドを使うときは-cで文字列として渡さないといけないらしい
    command: >
      /bin/sh -c "crontab /Amatsukaze/cron/entry.txt && cron -f"